# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'

jobs:
  build:

    runs-on: ubuntu-24.04-arm

    defaults:
      run:
        working-directory: ./backend/src/MotivationMachineFunctions

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish -c Release -o ../motivation_machine -r linux-arm64 --self-contained
    - name: Set up dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gnupg software-properties-common curl
    - name: Add HashiCorp GPG key
      run: |
        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
    - name: Add HashiCorp repository
      run: |
        sudo apt-add-repository "deb [arch=arm64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
    - name: Install Terraform
      run: |
        sudo apt-get update
        sudo apt-get install terraform
    - name: Verify Terraform installation
      run: terraform version
    - name: Set up cloud provider credentials
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Terraform
      run: |
        cd ../../terraform
        terraform init
        terraform apply -auto-approve
